scenario: telecom_cs_agent

baseline_tools:
- subscription_lookup
- usage_history
- billing_lookup
- device_info_lookup
- coverage_check
- change_plan
- cancel_subscription
- apply_discount
- create_service_note
- kb_search_trusted

llm:
  provider: gemini
  model: gemini-2.5-flash
  api_key_file: API_Key/gemini_api_key

# llm:
#   provider: openai_compat : gemma
#   model: llama3.1
#   base_url: http://localhost:11434/v1/
#   api_key: ollama    

# llm:
#   provider: "ollama"
#   model: "qwen2.5"     # <-- change like this (if you have the 14b version, use "qwen2.5:14b")
#   base_url: "http://localhost:11434/v1"
#   api_key: "ollama"

logging:
  base_dir: red_teaming/run/logs

runner:
  max_steps: 10

modes:
  attack:
    paths:
      system_prompt: scenarios/telecom_cs_agent/system.txt
      tasks: red_teaming/generated_tasks/telecom_cs_agent/2026-04-27/tasks_attack.jsonl
      tools: red_teaming/generated_tasks/telecom_cs_agent/2026-04-27/allow_tool.json
